sudo: required
dist: trusty
language: generic
env:
  - ROS_DISTRO=indigo   DOCKER_IMAGE=ubuntu:trusty
  - ROS_DISTRO=jade     DOCKER_IMAGE=ubuntu:trusty
  - ROS_DISTRO=kinetic  DOCKER_IMAGE=ubuntu:xenial
# matrix:
#   allow_failures:
#     - env: ROS_DISTRO=jade
# Install system dependencies, namely ROS.
script:
  # Define some config vars.
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - docker run --rm -i -v $CI_SOURCE_PATH:$CI_SOURCE_PATH -e "CI_SOURCE_PATH=$CI_SOURCE_PATH" -e "HOME=$HOME" -e "ROS_DISTRO=$ROS_DISTRO" -t $DOCKER_IMAGE sh -c "cd $CI_SOURCE_PATH; ./.travis.sh"

after_failure:
  - find ${HOME}/.ros/test_results -type f -exec echo "== {} ==" \; -exec cat {} \;
  - for file in ${HOME}/.ros/log/rostest-*; do echo "=== $file ==="; cat $file; done
